version: '3.9'

services:
  hivee-app-prod:
    container_name: hivee-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      host.docker.internal: host-gateway