version: '3.9'

services:
  hivee-app-dev:
    container_name: hivee-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    extra_hosts:
      host.docker.internal: host-gateway
    # environment:
    #   - CHOKIDAR_USEPOLLING=true